# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            'Marco Antonio'
tagline:          'Marco Antonio'
description:      'Senior software engineer'
url:              https://marcofognog.github.io/
baseurl:          ""

author:
  name:           'Marco Antonio'
  url:            https://twitter.com/marcofognog

paginate:         5

# Custom vars
version:          2.1.0
